---
Name: menuconfig
Only:
  moduleexists: silverstripe/subsite
---
gorriecoe\Menu\Models\MenuSet:
  extensions:
    - gorriecoe\Menu\Extensions\MenuSetSubsiteExtension
---
# Template provider registration
SilverStripe\View\TemplateGlobalProvider:
  providers:
    - gorriecoe\Menu\View\MenuManagerTemplateProvider
